version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - PGDATA=/var/lib/postgresql/data/market
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=secrect
    ports:
      - "5432:5432"
    volumes:
      - ./data/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local
